version: '3.6'

services:
  app:
    image: sillywhale/jirafeau:latest
    ports:
      - 80:80
    volumes:
      - ${PWD}/data/config.local.php:/Jirafeau/lib/config.local.php
      - ${PWD}/data/uploads:/jirafeau-data/

