version: '3.6'

services:
  app:
    image: docker.fricouv.eu/vfricou/nextcloud:latest
    ports:
      - :80
    volumes:
      - /srv/docker-data/nextcloud/data/apps:/nextcloud/apps
      - /srv/docker-data/nextcloud/data/config.php:/nextcloud/config/config.php
      - /srv/docker-data/nextcloud/data/nextcloud-data:/nextcloud-data
